# Generated by Django 3.0.5 on 2020-06-08 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=datetime.datetime(2020, 6, 8, 11, 5, 31, 503713, tzinfo=utc))),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('article_link', models.URLField()),
            ],
        ),
    ]
